apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:latest
          imagePullPolicy: IfNotPresent
          args:
            - redpanda
            - start
            - --mode=dev-container
            - --smp=1
            - --memory=256M
            - --reserve-memory=0M
            - --overprovisioned
            - --node-id=0
            - --check=false
            - --kafka-addr=PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr=PLAINTEXT://kafka:9092
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: redpanda-data
              mountPath: /var/lib/redpanda/data
      volumes:
        - name: redpanda-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092